/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* SysInt_1 */
#define SysInt_1__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1__INTC_NUMBER 146u
#define SysInt_1_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1_INTC_NUMBER 146u

/* ADC_1_IRQ */
#define ADC_1_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_1_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_1_IRQ__INTC_NUMBER 138u
#define ADC_1_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_1_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_1_IRQ_INTC_NUMBER 138u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

/* BLE_1_bless_isr */
#define BLE_1_bless_isr__INTC_CORTEXM4_ASSIGNED 1
#define BLE_1_bless_isr__INTC_CORTEXM4_PRIORITY 7u
#define BLE_1_bless_isr__INTC_NUMBER 24u
#define BLE_1_bless_isr_INTC_CORTEXM4_ASSIGNED 1
#define BLE_1_bless_isr_INTC_CORTEXM4_PRIORITY 7u
#define BLE_1_bless_isr_INTC_NUMBER 24u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
